name: attendance
description: "A software to check attendance."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  icons_launcher: ^2.1.6
  url_launcher: ^6.2.1
  provider: ^6.1.1
  bitsdojo_window: ^0.1.5
  integrate_platform: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

icons_launcher:
  image_path: 'assets/icons/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
