name: attendance
description: "A software to check attendance."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+3

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.14
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  icons_launcher: ^2.1.6
  url_launcher: ^6.2.1
  provider: ^6.1.1
  bitsdojo_window: ^0.1.5
  file_picker: ^5.2.10
  path_provider: ^2.1.1
  shirne_dialog: ^4.7.1
  animated_custom_dropdown: ^2.0.0
  dio: ^5.4.0
  open_filex: ^4.3.4
  share_plus: ^6.3.4
  permission_handler: ^11.1.0
  network_info_plus: ^3.0.5
  socket_io_client: ^1.0.2
  socket_io: ^1.0.1
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

icons_launcher:
  image_path: 'assets/icons/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
